doc: modeslib_doc.tex
	latex modeslib_doc
	bibtex modeslib_doc
	latex modeslib_doc
	latex modeslib_doc
	dvipdf  modeslib_doc.dvi  modeslib_doc.pdf
clean:
	\rm modeslib_doc.aux modeslib_doc.bbl modeslib_doc.blg modeslib_doc.dvi modeslib_doc.log
